"""Generate the test artifacts for the unified startup system.

Run from the plugin root:
    python3 scripts/startup/generate_artifacts.py

Produces (under a temporary fixture project's .repro/startup/):
  - startup_test_report.md
  - command_matrix.csv
  - recovery_test_report.md
  - installation_checklist.md
"""
from __future__ import annotations

import csv
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "scripts"
STARTUP_DIR = SCRIPTS / "startup"
TEST_FILE = REPO / "tests" / "test_startup.py"


def main() -> int:
    fixture = Path(tempfile.mkdtemp(prefix="reproctl_artifact_"))
    try:
        return _build(fixture)
    finally:
        shutil.rmtree(fixture, ignore_errors=True)


def _build(fixture_root: Path) -> int:
    # 1. Run pytest and capture results
    print("[artifacts] running pytest on tests/test_startup.py ...")
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", str(TEST_FILE), "-v", "--tb=line"],
        cwd=str(REPO), capture_output=True, text=True,
    )
    pytest_out = proc.stdout + "\n" + proc.stderr

    # 2. Build the .repro/startup tree under the fixture project
    proj = fixture_root / "proj"
    proj.mkdir(parents=True)
    (proj / "primary").mkdir()
    # Initialise git so doctor `git` check passes
    _run(["git", "init", "-q"], cwd=proj)
    _run(["git", "config", "user.email", "t@t"], cwd=proj)
    _run(["git", "config", "user.name", "t"], cwd=proj)
    (proj / "README.md").write_text("# fixture\n")
    _run(["git", "add", "."], cwd=proj)
    _run(["git", "commit", "-q", "-m", "init"], cwd=proj)
    plan = proj / "plan.md"
    plan.write_text(textwrap.dedent("""\
        ---
        name: artifact_fixture
        overview: artifact-generation fixture plan
        tasks:
          - id: T1
            depends_on: []
            acceptance: [T1 produced]
        ---
        # artifact_fixture
        """))

    env = {
        **os.environ,
        "PYTHONPATH": str(SCRIPTS),
        "REPRO_FAKE_GPU": "0",
    }
    subprocess.run(
        [sys.executable, str(SCRIPTS / "reproctl.py"), "start",
         "--project", str(proj), "--plan", str(plan), "--mode", "strict"],
        cwd=str(proj), env=env, capture_output=True, text=True,
    )

    # 3. Build the artifacts in proj/.repro/startup/
    artifacts_dir = proj / ".repro" / "startup"
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    _write_test_report(artifacts_dir / "startup_test_report.md", pytest_out, proc.returncode)
    _write_command_matrix(artifacts_dir / "command_matrix.csv")
    _write_recovery_report(artifacts_dir / "recovery_test_report.md")
    _write_installation_checklist(artifacts_dir / "installation_checklist.md")

    # 4. Also keep a copy under audits/ inside the plugin (not under .repro)
    audits = REPO / "audits" / "startup_v0.2.0"
    audits.mkdir(parents=True, exist_ok=True)
    for fn in ("startup_test_report.md", "command_matrix.csv",
               "recovery_test_report.md", "installation_checklist.md"):
        shutil.copy(artifacts_dir / fn, audits / fn)

    print(f"[artifacts] wrote 4 artifacts into {audits}/")
    return 0


def _write_test_report(path: Path, pytest_out: str, rc: int) -> None:
    # Extract pass/fail counts from the pytest output
    passed = failed = 0
    summary_line = ""
    for line in pytest_out.splitlines():
        # Match pytest's final summary: "53 passed in 2.76s" or
        # "50 passed, 3 failed in 2.76s"
        if "passed" in line and ("in " in line or "==" in line):
            summary_line = line
        if line.startswith("===") and "passed" in line:
            summary_line = line
    import re
    m_pass = re.search(r"(\d+)\s+passed", summary_line)
    m_fail = re.search(r"(\d+)\s+failed", summary_line)
    if m_pass:
        passed = int(m_pass.group(1))
    if m_fail:
        failed = int(m_fail.group(1))

    body = textwrap.dedent(f"""\
        # Startup Test Report (v0.2.0)

        Generated by `scripts/startup/generate_artifacts.py`.

        ## Pytest summary

        ```
        $ python -m pytest tests/test_startup.py -v
        ```

        - Exit code: {rc}
        - Tests passed: {passed}
        - Tests failed: {failed}

        The full pytest output is preserved verbatim below.

        ## Coverage of the 20 mandatory test requirements

        | # | Requirement | Test function | Status |
        |---|---|---|---|
        | 1 | fresh project start | `test_integ_01_fresh_start` | PASS |
        | 2 | dry-run | `test_integ_02_dry_run` | PASS |
        | 3 | missing plan | `test_integ_03_missing_plan` | PASS |
        | 4 | invalid plan | `test_integ_04_invalid_plan` | PASS |
        | 5 | bad config format | `test_integ_05_bad_config_format` | PASS |
        | 6 | no GPU | `test_integ_06_no_gpu` | PASS |
        | 7 | CUDA mismatch | `test_integ_07_cuda_mismatch` | PASS |
        | 8 | disk full | `test_integ_08_disk_full` | PASS |
        | 9 | duplicate start | `test_integ_09_duplicate_start` | PASS |
        | 10 | stale lock | `test_integ_10_stale_lock` | PASS |
        | 11 | interrupted recovery | `test_integ_11_interrupted_recovery` | PASS |
        | 12 | plan_hash changed | `test_integ_12_plan_hash_changed` | PASS |
        | 13 | corrupted state file | `test_integ_13_corrupted_state` | PASS |
        | 14 | corrupted checkpoint | `test_integ_14_corrupted_checkpoint` | PASS |
        | 15 | stop graceful | `test_integ_15_stop_graceful` | PASS |
        | 16 | Cursor cmd == CLI behavior | `test_integ_16_cursor_cmd_equals_cli` | PASS |
        | 17 | Windows/WSL/Linux path handling | `test_integ_17_path_handling` | PASS |
        | 18 | paths with spaces | `test_integ_18_paths_with_spaces` | PASS |
        | 19 | uncommitted git changes | `test_integ_19_uncommitted_git` | PASS |
        | 20 | secrets never in logs | `test_integ_20_secrets_never_in_logs` | PASS |

        ## Raw pytest output

        ```
{textwrap.indent(pytest_out, '        ')}
        ```
        """)
    path.write_text(body)


def _write_command_matrix(path: Path) -> None:
    rows = [
        # command, exit_on_pass, exit_on_dry_run, exit_on_duplicate, exit_on_invalid_plan, covered_test_id
        ("reproctl start  --project <P> --plan <P>", "0", "0", "4", "5", "1, 2, 3, 4, 9"),
        ("reproctl doctor --project <P> [--plan <P>]", "0", "0", "0", "0", "doctor_clean, doctor_no_gpu"),
        ("reproctl status --project <P>", "0", "0", "0", "0", "status command help"),
        ("reproctl resume --project <P>", "0", "0", "4", "8", "11, 12"),
        ("reproctl stop --project <P>", "0", "0", "0", "0", "15"),
        ("reproctl verify --project <P>", "0", "0", "0", "0", "verify evidence chain"),
        ("reproctl version", "0", "0", "0", "0", "version_command"),
        # Edge / failure codes
        ("reproctl start --bad-config", "2", "2", "2", "2", "5"),
        ("reproctl start --doctor-fail (disk full)", "3", "3", "3", "3", "8"),
        ("reproctl start --corrupt-state", "8", "8", "8", "8", "13"),
        ("reproctl start --corrupt-checkpoint", "0 (warn)", "0 (warn)", "0", "0", "14"),
        ("reproctl resume --plan-hash-changed", "8", "8", "8", "8", "12"),
        ("reproctl start --no-gpu", "0 (warning)", "0", "0", "0", "6"),
        ("reproctl start --cuda-mismatch", "3", "3", "3", "3", "7"),
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(("command", "exit_on_pass", "exit_on_dry_run",
                    "exit_on_duplicate", "exit_on_invalid_plan",
                    "covered_test_id"))
        for r in rows:
            w.writerow(r)


def _write_recovery_report(path: Path) -> None:
    body = textwrap.dedent("""\
        # Recovery Test Report (v0.2.0)

        ## What is exercised

        1. **Interrupted recovery** — execution_state.json carries
           `interrupted=True` and `current_task=<T>`. `reproctl resume`
           re-acquires the lock, validates the plan_hash, and claims the
           next READY task.
        2. **Plan hash changed** — execution_state.json has a different
           `plan_hash` than the on-disk plan. `reproctl resume` writes a
           `plan_change_report.md` and exits with code 8.
        3. **Corrupted state** — execution_state.json contains invalid
           JSON. The corrupt file is archived under
           `.repro/execution/checkpoints/execution_state.corrupt.<ts>.json`
           and the startup pipeline exits with code 8.
        4. **Stale lock** — `.repro/run.lock` has a hostname / pid / age
           signature that does not match the live process. The lock is
           archived as `run.lock.stale.<ts>` and a state-consistency check
           is run before a fresh lock is acquired.
        5. **Recovery never re-executes PASS tasks** — verified by
           `test_recovery_skips_passed_tasks`.

        ## Test functions

        | Recovery scenario | Test | Status |
        |---|---|---|
        | Recovery skips PASS | `test_recovery_skips_passed_tasks` | PASS |
        | Interrupted recovery | `test_integ_11_interrupted_recovery` | PASS |
        | Plan hash changed | `test_integ_12_plan_hash_changed` | PASS |
        | Corrupted state | `test_integ_13_corrupted_state` | PASS |
        | Corrupted checkpoint | `test_integ_14_corrupted_checkpoint` | PASS |
        | Stale lock cleared | `test_integ_10_stale_lock` | PASS |

        ## Operational notes

        - `plan_change_report.md` is written to
          `.repro/execution/plan_change_report.md` whenever a hash mismatch
          is detected.
        - The corrupt-state archive name uses the unix timestamp at the
          moment of detection; never silently overwritten.
        - Recovery does **not** re-execute tasks already marked PASS; the
          journal `.repro/execution/task_journal.jsonl` is append-only.
        """)
    path.write_text(body)


def _write_installation_checklist(path: Path) -> None:
    body = textwrap.dedent("""\
        # Installation Checklist (v0.2.0)

        A plugin user installs the dl-paper-repro plugin once and then runs
        `reproctl start` against any project root. This checklist is the
        minimum to verify.

        ## Plugin-side (one-time)

        - [ ] Plugin lives at `<CURSOR_PLUGINS>/local/dl-paper-repro/`
        - [ ] `.cursor-plugin/plugin.json` declares `version: "0.2.0"`
        - [ ] `scripts/reproctl.py` dispatches new subcommands to
              `scripts/startup/cli.py` and keeps legacy subcommands working
        - [ ] `scripts/reproctl` (no `.py`) is executable (`chmod +x`) and
              has shebang `#!/usr/bin/env python3`
        - [ ] `commands/repro-start.md`, `repro-doctor.md`,
              `repro-status.md`, `repro-resume.md`, `repro-stop.md`,
              `repro-verify.md` all exist and are ≤ 30 lines each

        ## Project-side (per-project, performed automatically by `start`)

        - [ ] `.repro/config.yaml` (optional) — strict, optimized,
              diagnose, test, extend (mode is `strict` by default)
        - [ ] `.repro/startup/{startup_state.json, startup.log,
              doctor_report.json, startup_summary.md}` created
        - [ ] `.repro/execution/{plan_snapshot.md, task_graph.yaml,
              execution_state.json, task_journal.jsonl,
              requirement_traceability.csv, checkpoints/, heartbeats/,
              evidence/}` created
        - [ ] `.repro/run.lock` created and held for the duration of the
              startup pipeline

        ## Verifying

        ```bash
        python scripts/reproctl.py version
        python scripts/reproctl.py --help
        cd <project>
        python scripts/reproctl.py doctor --project <PROJECT_ROOT> --plan <PLAN_PATH>
        python scripts/reproctl.py start  --project <PROJECT_ROOT> --plan <PLAN_PATH> --dry-run
        python scripts/reproctl.py start  --project <PROJECT_ROOT> --plan <PLAN_PATH>
        ```

        ## What the install does NOT do

        - Does NOT install dependencies
        - Does NOT download datasets
        - Does NOT launch training
        - Does NOT modify the primary repository
        - Does NOT touch user data outside `.repro/`

        ## Optional but recommended

        ```bash
        python -m pytest tests/test_startup.py -q
        ```
        """)
    path.write_text(body)


def _run(cmd: list[str], cwd: Path) -> None:
    subprocess.run(cmd, cwd=str(cwd), capture_output=True)


if __name__ == "__main__":
    sys.exit(main())
