"""
Metric Protocol Auditor (MPA) - Package Initialization
"""
from .models import (
    MetricDefinition,
    MetricObservation,
    MetricProtocolFingerprint,
    MetricSource,
    MetricConflict,
    RunManifest,
    MetricStatus,
    SourceRole,
    TaskType,
    Direction,
    Unit,
    ClassAggregation,
    SampleAggregation,
    AbsentClassPolicy,
    PredictionLevel,
    EvaluationScope,
    ProjectVerdict,
    ConflictType,
    ProtocolCompatibility,
    DatasetVersion,
    DataSubset,
    SplitName,
    SiamKPConv_CLASS_NAMES,
    SiamKPConv_NUM_CLASSES,
    SiamKPConv_CHANGE_CLASSES,
    SiamKPConv_PAPER_TARGETS,
    SiamKPConv_PAPER_TARGET_STD,
    SiamKPConv_MIOU_CH_TARGET,
    SiamKPConv_MIOU_CH_STD,
    SiamKPConv_MACC_TARGET,
    SiamKPConv_MACC_STD,
    SiamKPConv_PAPER_METADATA,
    WRONG_DOIS,
)
from .schemas import validate_schema, load_schema, save_schemas
from .registry import MetricRegistry, get_standard_metrics, create_miou_ch_definition
from .recompute import MetricRecomputer
from .conflict_detector import ConflictDetector
from .hardcode_detector import HardcodeDetector
from .golden_test import SiamKPConvGoldenTest, run_golden_test

__all__ = [
    # Models
    "MetricDefinition",
    "MetricObservation",
    "MetricProtocolFingerprint",
    "MetricSource",
    "MetricConflict",
    "RunManifest",
    # Enums
    "MetricStatus",
    "SourceRole",
    "TaskType",
    "Direction",
    "Unit",
    "ClassAggregation",
    "SampleAggregation",
    "AbsentClassPolicy",
    "PredictionLevel",
    "EvaluationScope",
    "ProjectVerdict",
    "ConflictType",
    "ProtocolCompatibility",
    "DatasetVersion",
    "DataSubset",
    "SplitName",
    # SiamKPConv Constants
    "SiamKPConv_CLASS_NAMES",
    "SiamKPConv_NUM_CLASSES",
    "SiamKPConv_CHANGE_CLASSES",
    "SiamKPConv_PAPER_TARGETS",
    "SiamKPConv_PAPER_TARGET_STD",
    "SiamKPConv_MIOU_CH_TARGET",
    "SiamKPConv_MIOU_CH_STD",
    "SiamKPConv_MACC_TARGET",
    "SiamKPConv_MACC_STD",
    "SiamKPConv_PAPER_METADATA",
    "WRONG_DOIS",
    # Functions
    "validate_schema",
    "load_schema",
    "save_schemas",
    "MetricRegistry",
    "get_standard_metrics",
    "create_miou_ch_definition",
    "MetricRecomputer",
    "ConflictDetector",
    "HardcodeDetector",
    "SiamKPConvGoldenTest",
    "run_golden_test",
]
